### ISSUE TITLE
How to do an inital load of the articles and not get banned by Arxiv?

### ISSUE THREAD

**Issue by Dabbrivia** [ranihorev/scihive-backend#4]
I have tried out arxiv_sanity_preserver initial load that is just scraping arxiv and (as expected) got banned after approx 1000 articles downloaded. The issue https://github.com/karpathy/arxiv-sanity-preserver/issues/58 stays unresolved/closed there. 

Now I have seen your front-end https://www.scihive.org/home which is much more advanced! So I just want to make sure the same ban will not happen here.

How do you handle the initial load in this project? 

I see a function [download_source_file](https://github.com/ranihorev/scihive-backend/blob/b0ff092212dfb2d790c854dfbef130ee595b0822/routes/latex_utils.py#L57) but it seems to get data from arxiv online as well, correct? Arxiv urges users to use their tarballs from S3 bucket instead https://arxiv.org/help/bulk_data_s3. Do you have a solution for this in your code or is it a non-issue for you for some other reason? It would be helpful to understand your approach. Thanks!

**Comment by Dabbrivia** [comment]
I would be willing to commit some time and write the S3 requester-pays code if that would help.

**Comment by ranihorev** [comment]
Take a look at the code here:
https://github.com/ranihorev/scihive-backend/blob/master/tasks/fetch_papers.py

Let me know if you have questions

**Comment by Dabbrivia** [comment]
> We're fetching 200 papers at a time and then sleep for 5 seconds

I saw that here 
`    parser.add_argument('--results-per-iteration', type=int, default=200, help='passed to arxiv API')
    parser.add_argument('--wait-time', type=float, default=5.0, help='lets be gentle to arxiv API (in number of seconds)')
`
If I'm not mistaken this is similar to what the orginal arxiv-sanity-preserver code [fetch_papers](https://github.com/karpathy/arxiv-sanity-preserver/blob/master/fetch_papers.py) does. As I mentioned above my instance got banned after aprox. 1000 pdfs downloaded. 

But even if it would not get banned for 1K it just doesn't scale, does it? I have downloaded metadata for cond-mat. Since the year 2000 its about 200k articles!

Currently I have downloaded all the Arxiv papers via S3 (~1Mln articles, 1,3TB) and just decided to create full text and  thumbnails for all those pdf. It is done via a shell script  I guess I will have to tweak the code a bit so it can fetch those from the disk.  

`function create_txt_and_thumbs {
filename="$1"
[ ! -f "${filename%.*}".txt ] && (pdftotext $filename "${filename%.*}".txt)
[ ! -f "${filename%.*}".jpg ] && (convert $filename[0-7] -thumbnail x156 "${filename%.*}".png;montage -mode concatenate -quality 80 -tile x1 "${filename%.*}"*.png "${filename%.*}".jpg;rm "${filename%.*}"*.png)
}
export -f create_txt_and_thumbs

time find /data/pdfs/ -type f -name "*.pdf"|parallel create_txt_and_thumbs {}`

**Comment by ranihorev** [comment]
Good luck!
Let us know if we can help with anything
